### PR TITLE
User can register via signup form

### PR DESCRIPTION
**Pull request by Abhishek3098**
In this commit user can register by using signup form

### CODE REVIEW

**Review by rdravidpatel — COMMENTED** [review]
this commit has no changes so can you please see what's wrong?

**Comment by Abhishek3098** [comment]
Ohh, by mistake I uploaded the wrong folder. Sorry I will upload new folder.

**Review by rdravidpatel — COMMENTED** [review]
All things are fine but it is only doing signup, right? because I cannot do sign in in this.

**Comment by Abhishek3098** [comment]
Yes it is only doing register for now in next commit signin will work.

**Pull request merged**
