### PR TITLE
Made Signout Method

### PR DESCRIPTION
**Pull request by Abhishek3098**
User needs to sign-off button to sign-out from the account

### CODE REVIEW

**Review by rdravidpatel — COMMENTED** [review]
Code looks good but by did you made signout method first, I mean without signin. Is there any reason behind that?

**Comment by Abhishek3098** [comment]
Yes, because I just want to be sure that we are doing the things in proper flow.

**Comment by rdravidpatel** [comment]
Okay, are you talking about the flow that we made before started working on the application?

**Comment by Abhishek3098** [comment]
Yes, that's what I am talking about.

**Pull request merged**
